### ISSUE TITLE
emacs segfaults when emacs-libvterm is loaded

### ISSUE THREAD

**Issue by thisch** [akermu/emacs-libvterm#232]
I've not yet managed to test emacs-libvterm due to a segfault.

For my tests I use emacs-libvterm with emacs 27 on ubuntu 19.10.
With this simple command I can easily trigger the segfault:

```
> $ gdb --args emacs -Q -L /home/thomas/gitrepos/emacs-libvterm -L /home/thomas/gitrepos/emacs-libvterm/build --eval \(require\ \'vterm\) --eval \(vterm\)

GNU gdb (Ubuntu 8.3-0ubuntu1) 8.3
Copyright (C) 2019 Free Software Foundation, Inc.
License GPLv3+: GNU GPL version 3 or later <http://gnu.org/licenses/gpl.html>
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
Type "show copying" and "show warranty" for details.
This GDB was configured as "x86_64-linux-gnu".
Type "show configuration" for configuration details.
For bug reporting instructions, please see:
<http://www.gnu.org/software/gdb/bugs/>.
Find the GDB manual and other documentation resources online at:
    <http://www.gnu.org/software/gdb/documentation/>.

For help, type "help".
Type "apropos word" to search for commands related to "word"...
Reading symbols from emacs...
(No debugging symbols found in emacs)
(gdb) run
Starting program: /usr/bin/emacs -Q -L /home/thomas/gitrepos/emacs-libvterm -L /home/thomas/gitrepos/emacs-libvterm/build --eval \(require\ \'vterm\) --eval \(vterm\)
[Thread debugging using libthread_db enabled]
Using host libthread_db library "/lib/x86_64-linux-gnu/libthread_db.so.1".
[New Thread 0x7fffec084700 (LWP 18390)]
[New Thread 0x7fffeb80a700 (LWP 18391)]
[New Thread 0x7fffeace3700 (LWP 18392)]
warning: Corrupted shared library list: 0x555556377320 != 0x555556053170
warning: Corrupted shared library list: 0x555556377320 != 0x555556053170
warning: Corrupted shared library list: 0x555556377320 != 0x555556053170
[New Thread 0x7fffe9eee700 (LWP 18393)]

Thread 1 "emacs" received signal SIGSEGV, Segmentation fault.
0x00007fffe961ebb4 in emacs_module_init (ert=0x7fffffffa410) at /home/thomas/gitrepos/emacs-libvterm/vterm-module.c:1105
1105	  Qt = env->make_global_ref(env, env->intern(env, "t"));
(gdb) bt
#0  0x00007fffe961ebb4 in emacs_module_init (ert=0x7fffffffa410) at /home/thomas/gitrepos/emacs-libvterm/vterm-module.c:1105
#1  0x000055555572a5ab in  ()
#2  0x000055555572626d in  ()
#3  0x00005555557268fa in  ()
#4  0x000055555570dec7 in  ()
#5  0x0000555555701f32 in  ()
#6  0x000055555570210d in  ()
#7  0x0000555555701d69 in  ()
#8  0x0000555555725ac0 in  ()
#9  0x0000555555726a23 in  ()
#10 0x00005555556ffcb3 in  ()
#11 0x0000555555734ce9 in  ()
#12 0x000055555570247a in  ()
#13 0x00005555556ffc0f in  ()
#14 0x0000555555702ad9 in  ()
#15 0x0000555555726519 in  ()
#16 0x00005555557268fa in  ()
#17 0x000055555570dec7 in  ()
#18 0x0000555555701f32 in  ()
#19 0x0000555555703898 in  ()
#20 0x00005555556ffcb3 in  ()
#21 0x0000555555734ce9 in  ()
#22 0x00005555556ffc0f in  ()
#23 0x0000555555734ce9 in  ()
--Type <RET> for more, q to quit, c to continue without paging--q
Quit
(gdb) q
```

**Comment by jixiuf** [comment]
#164 
And there is a section about ubuntu in readme
https://github.com/akermu/emacs-libvterm#vterm-and-ubuntu

**Comment by thisch** [comment]
The info in the readme didn't help me:
cmake is >= 3.11 and the emacs binary from the ubuntu-elisp ppa is compiled with module support.

But this comment helped me: https://github.com/akermu/emacs-libvterm/issues/185#issuecomment-562237077
@Honeypot95 may I ask, have you created an issue for this in the snapshot ppa already?

**Comment by Sbozzolo** [comment]
We can add that to the readme.

Thanks for reporting this.


Thomas Hisch writes:

> The info in the readme didn't help me:
> cmake is >= 3.11 and the emacs binary from the ubuntu-elisp ppa is compiled with module support.
>
> But this comment helped me: https://github.com/akermu/emacs-libvterm/issues/185#issuecomment-562237077
> @Honeypot95 may I ask, have you created an issue for this in the snapshot ppa already?

**Comment by Honeypot95** [comment]
@thisch Hey, no, not yet. Even though I assume it takes less than 5 minutes, I haven't done it before, but I will look into it these following days.

**Comment by Sbozzolo** [comment]
I am closing this issue. We added a warning in the readme, and the bug seems to be upstream.
